# see: https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
argo-cd:
  controller:
    serviceAccount:
      create: false
      name: argocd-sa
  server:
    serviceAccount:
      create: false
      name: argocd-sa
